### ISSUE TITLE
Converge of windows 2008R2 fails with message: Failed to complete #converge action: [Unable to retrieve IPs]

### ISSUE THREAD

**Issue by johnsmyth** [mwrock/kitchen-nodes#16]
I'm getting an error trying to converge a windows 2008r2 machine with test kitchen,  The kitchen logs are pasted below.  It seems like it might have something to do with Get-NetIPConfiguration not seeming to be available in powershell 2 (https://github.com/mwrock/kitchen-nodes/blob/v0.4.0/lib%2Fkitchen%2Fprovisioner%2Fip_finder%2Fwinrm.rb#L24 ), however I *know* I've used kitchen-nodes with 2008r2 before without issue..... 

```
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0

```

```
I, [2016-03-04T16:34:23.098740 #21609]  INFO -- Kitchen: -----> Starting Kitchen (v1.5.0)
I, [2016-03-04T16:34:25.579370 #21609]  INFO -- Kitchen: -----> Creating <test-ad-dc>...
I, [2016-03-04T16:37:36.174724 #21609]  INFO -- Kitchen: -----> Converging <test-ad-dc>...
I, [2016-03-04T16:47:31.988985 #21609]  INFO -- Kitchen: -----> Creating <default-windows-2008r2>...
I, [2016-03-04T16:53:36.905845 #21609]  INFO -- Kitchen: -----> Converging <default-windows-2008r2>...
E, [2016-03-04T16:53:37.631345 #21609] ERROR -- Kitchen: ------Exception-------
E, [2016-03-04T16:53:37.631374 #21609] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-03-04T16:53:37.631388 #21609] ERROR -- Kitchen: Message: Failed to complete #converge action: [Unable to retrieve IPs]
E, [2016-03-04T16:53:37.631400 #21609] ERROR -- Kitchen: ---Nested Exception---
E, [2016-03-04T16:53:37.631411 #21609] ERROR -- Kitchen: Class: RuntimeError
E, [2016-03-04T16:53:37.631422 #21609] ERROR -- Kitchen: Message: Unable to retrieve IPs
E, [2016-03-04T16:53:37.631432 #21609] ERROR -- Kitchen: ------Backtrace-------
E, [2016-03-04T16:53:37.631442 #21609] ERROR -- Kitchen: /Users/jsmyth/.chefdk/gem/ruby/2.1.0/gems/kitchen-nodes-0.6.4/lib/kitchen/provisioner/nodes.rb:135:in `active_ips'
E, [2016-03-04T16:53:37.631470 #21609] ERROR -- Kitchen: /Users/jsmyth/.chefdk/gem/ruby/2.1.0/gems/kitchen-nodes-0.6.4/lib/kitchen/provisioner/nodes.rb:123:in `get_reachable_guest_address'
E, [2016-03-04T16:53:37.631483 #21609] ERROR -- Kitchen: /Users/jsmyth/.chefdk/gem/ruby/2.1.0/gems/kitchen-nodes-0.6.4/lib/kitchen/provisioner/nodes.rb:58:in `ipaddress'
E, [2016-03-04T16:53:37.631500 #21609] ERROR -- Kitchen: /Users/jsmyth/.chefdk/gem/ruby/2.1.0/gems/kitchen-nodes-0.6.4/lib/kitchen/provisioner/nodes.rb:103:in `node_template'
E, [2016-03-04T16:53:37.631512 #21609] ERROR -- Kitchen: /Users/jsmyth/.chefdk/gem/ruby/2.1.0/gems/kitchen-nodes-0.6.4/lib/kitchen/provisioner/nodes.rb:41:in `create_node'
E, [2016-03-04T16:53:37.631523 #21609] ERROR -- Kitchen: /Users/jsmyth/.chefdk/gem/ruby/2.1.0/gems/kitchen-nodes-0.6.4/lib/kitchen/provisioner/nodes.rb:34:in `create_sandbox'
E, [2016-03-04T16:53:37.631533 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/provisioner/base.rb:63:in `call'
E, [2016-03-04T16:53:37.631544 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:373:in `block in converge_action'
E, [2016-03-04T16:53:37.631554 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:495:in `call'
E, [2016-03-04T16:53:37.631564 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:495:in `synchronize_or_call'
E, [2016-03-04T16:53:37.631575 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:460:in `block in action'
E, [2016-03-04T16:53:37.631585 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-03-04T16:53:37.631595 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:459:in `action'
E, [2016-03-04T16:53:37.631605 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:369:in `converge_action'
E, [2016-03-04T16:53:37.631615 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:348:in `block in transition_to'
E, [2016-03-04T16:53:37.631646 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:347:in `each'
E, [2016-03-04T16:53:37.631657 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:347:in `transition_to'
E, [2016-03-04T16:53:37.631667 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:138:in `converge'
E, [2016-03-04T16:53:37.631684 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:176:in `public_send'
E, [2016-03-04T16:53:37.631695 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2016-03-04T16:53:37.631706 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
E, [2016-03-04T16:53:37.631716 #21609] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'
E, [2016-03-04T16:53:37.631727 #21609] ERROR -- Kitchen: ----------------------
```

**Comment by mwrock** [comment]
No I'm afraid Win2k8R2 is not supported. At least not unless it's powershell version is updated to at least v3.
