### ISSUE TITLE
Net SCP error when using nodes

### ISSUE THREAD

**Issue by rneu31** [mwrock/kitchen-nodes#34]
Returning to a cookbook I wrote a few months ago... I now see this error:

```
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing nodes
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <linux-master-ra-centos-73>
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command': SCP did not finish successfully (1):  (Net::SCP::Error)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:607:in `do_close'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:564:in `channel_closed'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:675:in `channel_close'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:540:in `dispatch_incoming_packets'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:124:in `close'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:115:in `close'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:285:in `cleanup!'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:205:in `run_action_in_thread'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

```

Does this mean anything to anyone? If I use `chef_zero` provisioner this does not happen. I'm currently pretty stumped.

**Comment by rneu31** [comment]
Just ran `kitchen converge -l debug` and the error did not occur, after numerous non-debug runs in a row failing. Today isn't even Monday.

**Comment by rneu31** [comment]
It happens a few times in a row, then is okay for a little while, then happens again. Adding this sleep (probably much higher than it would actually need to be) seems to have fixed my problems. Insert Windows joke here.

```ruby
class Nodes < ChefZero
  def create_sandbox
    FileUtils.rm(node_file) if File.exist?(node_file)
    create_node
    sleep 5
  ensure
    super
  end
```
