### ISSUE TITLE
Sandbox not created errors?

### ISSUE THREAD

**Issue by nukepuppy** [mwrock/kitchen-nodes#5]
not sure why but when using nodes as provisioner always get the sandbox not created errors

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::Nodes#create_sandox before trying to access the path.]
```

any advice here?

Trying to run multiple 'usable' nodes (which can be connected to directly) and wanted to evaluate how the kitchen-nodes could help do some of this.

**Comment by mwrock** [comment]
interesting. Mind running with debug and sending the stack trace? 

Also what driver are you using?

Thanks!

**Comment by nukepuppy** [comment]
here is a trace
```
I, [2015-07-15T10:41:49.327832 #79966]  INFO -- Kitchen: -----> Starting Kitchen (v1.3.1)
D, [2015-07-15T10:41:49.336116 #79966] DEBUG -- Kitchen: [kitchen::driver::vagrant command] BEGIN (vagrant --version)
D, [2015-07-15T10:41:49.579047 #79966] DEBUG -- Kitchen: [kitchen::driver::vagrant command] END (0m0.19s)
I, [2015-07-15T10:41:49.867787 #79966]  INFO -- Kitchen: -----> Creating <default-centos-64>...
I, [2015-07-15T10:42:34.337032 #79966]  INFO -- Kitchen: -----> Converging <default-centos-64>...
D, [2015-07-15T10:42:34.339944 #79966] DEBUG -- Kitchen: ------Exception-------
D, [2015-07-15T10:42:34.339998 #79966] DEBUG -- Kitchen: Class: Kitchen::ActionFailed
D, [2015-07-15T10:42:34.340029 #79966] DEBUG -- Kitchen: Message: Failed to complete #converge action: [Sandbox directory has not yet been created. Please run Kitchen::Provisioner::Nodes#create_sandox before trying to access the path.]
D, [2015-07-15T10:42:34.340101 #79966] DEBUG -- Kitchen: ---Nested Exception---
D, [2015-07-15T10:42:34.340130 #79966] DEBUG -- Kitchen: Class: Kitchen::ClientError
D, [2015-07-15T10:42:34.340150 #79966] DEBUG -- Kitchen: Message: Sandbox directory has not yet been created. Please run Kitchen::Provisioner::Nodes#create_sandox before trying to access the path.
D, [2015-07-15T10:42:34.340175 #79966] DEBUG -- Kitchen: ------Backtrace-------
D, [2015-07-15T10:42:34.340194 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/base.rb:131:in `sandbox_path'
D, [2015-07-15T10:42:34.340213 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/provisioner/base.rb:140:in `cleanup_sandbox'
D, [2015-07-15T10:42:34.340231 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:53:in `ensure in converge'
D, [2015-07-15T10:42:34.340252 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:53:in `converge'
D, [2015-07-15T10:42:34.340271 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.15.0/lib/kitchen/driver/vagrant.rb:75:in `converge'
D, [2015-07-15T10:42:34.340289 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:352:in `public_send'
D, [2015-07-15T10:42:34.340348 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:352:in `block in perform_action'
D, [2015-07-15T10:42:34.340369 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:416:in `call'
D, [2015-07-15T10:42:34.340400 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:416:in `synchronize_or_call'
D, [2015-07-15T10:42:34.340420 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:381:in `block in action'
D, [2015-07-15T10:42:34.340448 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D, [2015-07-15T10:42:34.340479 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:380:in `action'
D, [2015-07-15T10:42:34.340529 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:352:in `perform_action'
D, [2015-07-15T10:42:34.340602 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:312:in `converge_action'
D, [2015-07-15T10:42:34.340647 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:292:in `block in transition_to'
D, [2015-07-15T10:42:34.340704 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:291:in `each'
D, [2015-07-15T10:42:34.340742 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:291:in `transition_to'
D, [2015-07-15T10:42:34.340789 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:130:in `converge'
D, [2015-07-15T10:42:34.340845 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
D, [2015-07-15T10:42:34.340917 #79966] DEBUG -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D, [2015-07-15T10:42:34.340965 #79966] DEBUG -- Kitchen: ----------------------
 ```

**Comment by mwrock** [comment]
I tried to reproduce this with no luck and then I noticed that you are using kitchen 1.3.1 and kitchen-nodes requires 1.4 at a minimum. So you could try upgrading your chef-dk.
